# Generated by Django 5.0.6 on 2024-06-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_manufactured_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateField(blank=True, help_text='Введите Дату производства продукта', null=True, verbose_name='Дата производства'),
        ),
    ]
