# Generated by Django 5.0.6 on 2024-09-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_product_manufactured_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, help_text='Введите Цену за покупку продукта', null=True, verbose_name='Цена за покупку'),
        ),
    ]
