# Generated by Django 5.0.6 on 2024-09-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Введите Дату создания продукта', null=True, verbose_name='Дата создания(записи в БД)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Введите Дату последнего изменения продукта', null=True, verbose_name='Дата последнего изменения(записи в БД)'),
        ),
    ]
